version: '3.7'
services:
  php:
    networks:
      - web-ci
    volumes:
      - .:/var/www/html/
  mariadb:
    networks:
      - web-ci
    environment:
      MYSQL_ROOT_PASSWORD: 'cirootpassword'
      MYSQL_DATABASE: 'cidatabase'
      MYSQL_USER: 'ciuser'
      MYSQL_PASSWORD: 'cipassword'

  node:
    image: node:lts
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    networks:
      - web-ci

networks:
  web-ci:
